squatix-node_src = squatix-node.c squatix-rule-one-slotframe.c squatix-rule-node-data-slotframe.c
#squatix-node_src = squatix-node.c squatix-rule-general-slotframe.c
#squatix-node_src = squatix-node.c squatix-rule-one-slotframe.c