#squatix-node_src = squatix-node.c squatix-rule-default-common.c #squatix-rule-eb-per-time-source.c squatix-rule-unicast-per-neighbor-rpl-storing.c #squatix-rule-unicast-per-neighbor-rpl-ns.c

squatix-node_src = squatix-node.c squatix-rule-default-common.c #squatix-rule-unicast-per-neighbor-rpl-storing.c 