#orchestra-node_src = orchestra-node.c orchestra-rule-default-common.c #orchestra-rule-eb-per-time-source.c orchestra-rule-unicast-per-neighbor-rpl-storing.c #orchestra-rule-unicast-per-neighbor-rpl-ns.c

orchestra-node_src = orchestra-node.c orchestra-rule-default-common.c orchestra-rule-unicast-per-neighbor-rpl-storing.c 